package.json
it fixes a node.js v17.8 compat issue
refs: https://github.com/iambumblehead/esmock/releases/tag/v1.7.5
=> chore: upgrade esmock

lib/init/config-initializer.js, lib/init/npm-utils.js, tests/init/npm-utils.js
Added yarn and pnpm for installing dependencies
I've used https://github.com/eslint/eslint/pull/13756 as base for this PR and added pnpm. I once tried to link `create-config` with eslint and things seemed to work fine with yarn berry version too.
fixes: https://github.com/eslint/create-config/issues/20
=> feat: added yarn and pnpm installations

lib/init/config-initializer.js, tests/init/config-initializer.js
Addresses: 
- https://github.com/eslint/create-config/issues/19
We will early exit when `package.json` is not found
=> fix: throw error and exit when `package.json` not found

lib/init/config-initializer.js, package.json, tests/init/config-initializer.js
as they do not officially support ts.
fixes #32
=> fix: remove airbnb/google in style guides when using ts

README.md, lib/init/config-initializer.js, package.json
=> feat: support `--config`

.github/workflows/ci.yml, tests/init/npm-utils.js
Adds Node v19 to `ci.yml`.
https://nodejs.org/en/blog/release/v19.0.0/
=> ci: add Node v19

README.md
Updated a sentence describing `--config` to be the same as in https://eslint.org/docs/head/user-guide/getting-started#installation-and-usage
=> docs: sync `--config` instructions in README with eslint Getting Started

.github/workflows/ci.yml
Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.
=> ci: use LTS node version in lint job

README.md
Updates `--config` examples in the README file to be the same as on https://eslint.org/docs/latest/use/getting-started
=> docs: sync `--config` examples with ESLint Getting Started docs

.github/workflows/release-please.yml
This updates the release process to also post on Mastodon.
Copy & paste from https://github.com/eslint/generator-eslint/pull/152
=> chore: Also post releases to Mastodon

.github/workflows/release-please.yml
`release-please` creates a release PR after it notices the default branch contains "releasable units" since the last release. By default, releasable units are commits tagged as `feat`, `fix`, or `deps` (we're not using this one). So, currently, we can release a new version only if there is at least one `feat` or `fix` commit since the last version.
Sometimes, we'd like to release a new version even if there are no `feat` or `fix` commits. In particular, in some cases when there are commits tagged with:
* `perf` - the new version will have better performance
* `chore` - we use `chore` for dependency upgrades too
* `docs` - to update README on npm
Also, only releasable units appear in changelogs, while we used to list all commits.
In the last TSC meeting, we decided to configure …
=> chore: include all commits in the changelog

.github/workflows/release-please.yml
Remove the `@` sign from the start of tweets/toots to ensure it's not marked as a mention.
=> chore: Update tweet message

.github/workflows/ci.yml, package.json
- run tests on Node.js v20
- Remove Node v19 and v17 from matrix
I feel it's fine to test on even node version only.
=> ci: run tests on Node.js v20

lib/init/config-initializer.js, tests/init/config-initializer.js
fixes https://github.com/eslint/eslint/discussions/17221
it's a bug when choosing vue+ts. to repro:
```bash
➜  $ npm init @eslint/config                                           
Need to install the following packages:
@eslint/create-config@0.4.3
Ok to proceed? (y) y
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · vue
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser
✔ What format do you want your config file to be in? · JavaScript
The config that you've selected requires the following dependencies:
eslint-plugin-vue@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest
✔ Would you like to install them now? · No / Yes
✔ Which package …
```
=> fix: generated vue-ts config

package.json, tests/patch-esmock.js
This PR fixes the unit tests on previous versions of Node.js (< 18). These tests are currently no longer working because of a breaking change in a dependency. See for example https://github.com/eslint/create-config/actions/runs/6609176505.
Unit tests in this package use esmock as a dev dependency.
- esmock < 2.4 works only on Node.js < 19.
- esmock >= 2.4 works only on Node.js >= 18.6.
(These is not officially specified information, I determined it by testing)
In order to run unit tests on all versions of Node.js that we need to support, I have created a postinstall script that checks the version of Node.js and replaces the esmock folder in node_modules with a legacy release on Node.js < 19.
=> chore: run tests on all supported versions of Node.js

lib/utils/logging.js
`log.warn` export was missing
https://github.com/eslint/create-config/blob/54ac1f2bb213e60c9b387c01cc674cb03b1aafed/lib/config-generator.js#L275
```
The config that you've selected requires the following dependencies:
eslint, globals, @eslint/js
√ Would you like to install them now? · No / Yes
Successfully created C:\projects\create-config\eslint.config.js file.
file:///C:/projects/create-config/lib/config-generator.js:275
log.warn("You will need to install the dependencies yourself.");
^
TypeError: log.warn is not a function
at ConfigGenerator.output (file:///C:/projects/create-config/lib/config-generator.js:275:17)
at async file:///C:/projects/create-config/bin/create-config.js:28:5
```
=> fix: add `log.warn`

.github/workflows/release-please.yml
another way is to remove `node-options=--loader=esmock` in `.npmrc`, and adding the env in npm scripts instead.
fixes https://github.com/eslint/create-config/issues/86
=> chore: run `npm install` before npm publish

lib/config-generator.js, tests/__snapshots__/style-esm-none-airbnb, tests/__snapshots__/style-esm-react-airbnb, tests/config-snapshots.spec.js
eslint-congif-airbnb is only used for react.
fixes #87
=> fix: use eslint-config-airbnb-base by default

lib/config-generator.js, tests/__snapshots__/style-esm-none-xo-typescript
The ts style guide typically depend on tseslint, so there's no need to install it separately. Doing so might result in multiple versions being installed, leading to errors.
fixes #97, #98
=> fix: not install multi tseslint versions

README.md
We've received a few reports generated configs seem to be eslintrc format, so I've updated the documentation to use the latest version.
refs: https://github.com/eslint/eslint/issues/18369, https://github.com/eslint/eslint/discussions/18361,
=> docs: use @eslint/create-config latest

.github/workflows/ci.yml
Updates CI workflow to run tests in Node.js 22 as well. Also bumps `actions/checkout` and `actions/setup-node` to v4 for the Lint job.
=> ci: run tests in Node.js 22

.npmrc, package.json, tests/utils/npm-utils.spec.js
Fix tests in Node.js 22.2.0 by using sinon to mock dependencies instead of esmock.
Fixes #116
=> test: replace esmock with sinon

lib/config-generator.js, tests/__snapshots__/problems-commonjs-none-typescript, tests/__snapshots__/problems-commonjs-vue-typescript, tests/__snapshots__/problems-esm-none-typescript, tests/__snapshots__/problems-esm-react-eslint8.x-typescript, tests/__snapshots__/problems-esm-vue-typescript, tests/__snapshots__/problems-script-none-typescript, tests/__snapshots__/problems-script-vue-typescript, tests/__snapshots__/syntax-commonjs-none-typescript, tests/__snapshots__/syntax-commonjs-vue-typescript, tests/__snapshots__/syntax-esm-none-typescript, tests/__snapshots__/syntax-esm-react-eslint8.x-typescript, tests/__snapshots__/syntax-esm-vue-typescript, tests/__snapshots__/syntax-script-none-typescript, tests/__snapshots__/syntax-script-vue-typescript
it does not suppport eslint v9 yet.
refs: https://github.com/eslint/create-config/issues/89#issuecomment-2118575800
fixes #120
=> fix: use `--force` to install eslint v9 + tseslint

lib/config-generator.js, tests/__snapshots__/problems-esm-react-eslint8.x-javascript, tests/__snapshots__/problems-esm-react-eslint8.x-typescript, tests/__snapshots__/problems-esm-react-eslint9.x-javascript, tests/__snapshots__/problems-esm-react-eslint9.x-typescript, tests/__snapshots__/syntax-esm-react-eslint8.x-javascript, tests/__snapshots__/syntax-esm-react-eslint8.x-typescript, tests/__snapshots__/syntax-esm-react-eslint9.x-javascript, tests/__snapshots__/syntax-esm-react-eslint9.x-typescript
I saw this problem mentioned several times in issues/discussions:
```
$ npx @eslint/create-config
√ How would you like to use ESLint? · problems    
√ What type of modules does your project use? · esm
√ Which framework does your project use? · react
√ The React plugin doesn't officially support ESLint v9 yet. What would you like to do? · 9.x
√ Does your project use TypeScript? · javascript
√ Where does your code run? · browser
The config that you've selected requires the following dependencies:
eslint@9.x, globals, @eslint/js, eslint-plugin-react, @eslint/compat
√ Would you like to install them now? · No / Yes
√ Which package manager do you want to use? · npm
☕️Installing...
...
Successfully created C:\projects\tmp\tmp\eslint.config.mjs file.
$ npx eslint a.jsx
C:\projects\tmp\tmp\a.jsx …
```
=> fix: enable linting `.jsx` files when React is selected

bin/create-config.js, eslint.config.js, lib/config-generator.js, lib/utils/npm-utils.js, package.json, tests/_utils/in-memory-fs.js, tests/config-snapshots.spec.js, tests/utils/npm-utils.spec.js
Switches to eslint-config-eslint v11.
Marked as refactor because there are changes in production code.
=> refactor: switch to eslint-config-eslint v11

lib/config-generator.js
fixes https://github.com/eslint/create-config/issues/125
=> fix: add warning message for ESLint v9 with npm `--force` flag

lib/config-generator.js, tests/__snapshots__/problems-commonjs-vue-typescript, tests/__snapshots__/problems-esm-vue-typescript, tests/__snapshots__/problems-script-vue-typescript, tests/__snapshots__/syntax-commonjs-vue-typescript, tests/__snapshots__/syntax-esm-vue-typescript, tests/__snapshots__/syntax-script-vue-typescript
This commit modifies the ESLint config generator to add a custom parser for TypeScript files when the language option is set to "typescript". This change is necessary to ensure proper linting of Vue files with TypeScript code.
refs: https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser
=> fix: Add custom ts parser for vue projects

tests/__snapshots__/config@eslint-config-xo, tests/config-snapshots.spec.js
The latest version of `eslint-config-xo` supports ESLint v9 and exports flat config format:
https://github.com/xojs/eslint-config-xo/releases/tag/v0.46.0
It currently breaks CI on the main branch:
https://github.com/eslint/create-config/actions/runs/10234823210/job/28314801941
This updates a test with `eslint-config-xo` to not use `--eslintrc`, and updates the corresponding snapshot accordingly.
=> test: update test with `eslint-config-xo`

lib/config-generator.js, tests/__snapshots__/empty, tests/config-snapshots.spec.js
As of v9.20.0, ESLint emits a warning when the config file exports an empty array.
This PR updates the output to export `[{}]` instead of `[]` when the config file is intentionally empty as the result of answers (e.g., https://github.com/eslint/eslint/issues/19044#issuecomment-2449269368) in order to avoid the warning.
=> feat: avoid empty config warning

bin/create-config.js, lib/config-generator.js, lib/utils/npm-utils.js, tests/config-snapshots.spec.js, tests/utils/npm-utils.spec.js
This PR enhances the `fetchPeerDependencies` function by adding a fallback mechanism. If `npm` is unavailable, the function will now query the npm registry API directly to fetch peer dependencies.
Closes #84
=> feat: add fallback to npm registry API in fetchPeerDependencies

lib/config-generator.js, tests/__snapshots__/config@eslint-config-xo
To determine whether the version of ESLint required by a shareable config exports `defineConfig()`, `@eslint/create-config` currently uses `semver.satisfies("9.22.0", range)` check.
However, the latest `eslint-config-xo` requires `"eslint": "^9.25.1"`, so ESLint v9.22.0 doesn't satisfy the requirements, and thus the check returns `false` and `@eslint/create-config` mistakenly imports `defineConfig()` from `@eslint/config-helpers`, as shown by the test failure on https://github.com/eslint/create-config/pull/167.
What `@eslint/create-config` should check is, I think, whether any of >= 9.22.0 is in the range, so I replaced the check with `!semver.gtr("9.22.0", range)`.
=> fix: semver calculations for `defineConfig` import

lib/config-generator.js, tests/__snapshots__/problems-commonjs-none-typescript, tests/__snapshots__/problems-commonjs-react-typescript, tests/__snapshots__/problems-commonjs-vue-typescript, tests/__snapshots__/problems-esm-none-typescript, tests/__snapshots__/problems-esm-react-typescript, tests/__snapshots__/problems-esm-vue-typescript, tests/__snapshots__/problems-script-none-typescript, tests/__snapshots__/problems-script-react-typescript, tests/__snapshots__/problems-script-vue-typescript, tests/__snapshots__/syntax-commonjs-none-typescript, tests/__snapshots__/syntax-commonjs-react-typescript, tests/__snapshots__/syntax-commonjs-vue-typescript, tests/__snapshots__/syntax-esm-none-typescript, tests/__snapshots__/syntax-esm-react-typescript, tests/__snapshots__/syntax-esm-vue-typescript, tests/__snapshots__/syntax-script-none-typescript, tests/__snapshots__/syntax-script-react-typescript, tests/__snapshots__/syntax-script-vue-typescript
Hello,
In this PR, I’ve added support for `.mts` and `.cts` file extensions in TypeScript configurations.
Currently, TypeScript recognizes both `.mts` and `.cts` as valid file extensions, but `create-config` only supports `.mjs` and `.cjs` for JavaScript.
According to the TypeScript documentation:
[https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection](https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection)
=> feat: add support for `.mts` and `.cts` extensions

lib/config-generator.js, tests/__snapshots__/esm-javascript-json-problems, tests/__snapshots__/problems-commonjs-none-javascript, tests/__snapshots__/problems-commonjs-none-typescript, tests/__snapshots__/problems-commonjs-react-javascript, tests/__snapshots__/problems-commonjs-react-typescript, tests/__snapshots__/problems-commonjs-vue-javascript, tests/__snapshots__/problems-commonjs-vue-typescript, tests/__snapshots__/problems-esm-none-javascript, tests/__snapshots__/problems-esm-none-typescript, tests/__snapshots__/problems-esm-react-javascript, tests/__snapshots__/problems-esm-react-typescript, tests/__snapshots__/problems-esm-vue-javascript, tests/__snapshots__/problems-esm-vue-typescript, tests/__snapshots__/problems-script-none-javascript, tests/__snapshots__/problems-script-none-typescript, tests/__snapshots__/problems-script-react-javascript, tests/__snapshots__/problems-script-react-typescript, tests/__snapshots__/problems-script-vue-javascript, tests/__snapshots__/problems-script-vue-typescript
When generating ESLint configs with environment globals, combine them into a single config object instead of creating separate objects. This simplifies the output and prevents potential confusion for users who might think multiple objects are necessary.
Fixes #171
=> refactor: combine environment config with base config

.github/workflows/add-to-triage.yml
Hi,
This PR is part of the process to centralize workflows. In this PR, I've added the add-to-triage.yml workflow, which uses the centralized workflow.
You can find more details about this workflow in https://github.com/eslint/workflows/issues/4 and https://github.com/eslint/workflows/pull/7.
=> ci: centralize `add-to-triage.yml`
